server {
    listen 80;
    server_name _;

    # Keycloak realms
    location /realms/ {
        proxy_pass http://keycloak:8080;
        proxy_set_header Host $host:8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Keycloak admin
    location /admin/ {
        proxy_pass http://keycloak:8080;
        proxy_set_header Host $host:8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Keycloak resources
    location /resources/ {
        proxy_pass http://keycloak:8080;
        proxy_set_header Host $host:8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # FastAPI
    location /api/ {
        proxy_pass http://host.docker.internal:8000;
        proxy_set_header Host $host:8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Default -> React
    location / {
        return 302 http://localhost:5173;
    }
}